# WS-C: Agent Runtime Terraform module
#
# PR #1 scope: enable Agent Platform + BigQuery APIs and provision the
# `agent_audit_log.events` table that every agent writes to (PRD §4.6).
#
# PR #3 scope (this PR): the `agent_outputs` dataset + four tables that WS-G
# agents and WS-D routing depend on (PRD §6.1, spec §3.1, §5–§8). Mixed
# canonicality is intentional and documented in ADR 0009.
#
# Deferred to later PRs in this workstream:
# - Reasoning Engine deployment template + Model Armor config (PR #2)
# - Agent Engine + Memory Bank instance (PR #2, paired with the runtime template)

# ---------------------------------------------------------------------------
# API enablement
# ---------------------------------------------------------------------------
# Foundation deliberately deferred these (terraform/modules/foundation/main.tf:43-62)
# to keep WS-A's blast radius small. WS-C owns the Agent Platform surface.

locals {
  agent_runtime_apis = [
    "aiplatform.googleapis.com",
    "bigquery.googleapis.com",
    "modelarmor.googleapis.com", # PRD §4.4 / ADR 0015 — Templates for required-armor agents
  ]
}

resource "google_project_service" "agent_runtime" {
  for_each = toset(local.agent_runtime_apis)

  project            = var.brain_project_id
  service            = each.value
  disable_on_destroy = false
}

# ---------------------------------------------------------------------------
# Application audit log (PRD §4.6 layer 2)
# ---------------------------------------------------------------------------
# Every agent invocation writes one row, success or failure, with the schema
# defined in PRD §4.6 plus a few fields the routing/observability layers will
# need (success, error, human_review_routed).
#
# No SA grants here. Each WS-G module grants its own agent SA write access on
# this table when the SA is created (PRD §4.2 SA topology).

resource "google_bigquery_dataset" "agent_audit_log" {
  project     = var.brain_project_id
  dataset_id  = "agent_audit_log"
  location    = "US"
  description = "WS-C: per-invocation agent audit events. PRD §4.6 layer 2."

  labels = {
    workstream = "agent_runtime"
    component  = "audit_log"
  }

  depends_on = [google_project_service.agent_runtime]
}

resource "google_bigquery_table" "events" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_audit_log.dataset_id
  table_id   = "events"

  description = "Per-agent-invocation audit row. Written by src/agency_brain/common/audit_log.py."

  # Partition by event timestamp so dashboards/alerts can scan recent windows
  # cheaply. Cluster by agent_id so per-agent queries don't full-scan.
  # ADR 0024: drop partitions older than 365 days. PRD §4.6 audit window.
  time_partitioning {
    type          = "DAY"
    field         = "timestamp"
    expiration_ms = 31536000000 # 365 days
  }
  clustering = ["agent_id"]

  schema = jsonencode([
    { name = "event_id", type = "STRING", mode = "REQUIRED",
    description = "UUIDv4 generated by the audit client." },
    { name = "timestamp", type = "TIMESTAMP", mode = "REQUIRED",
    description = "Event time in UTC. Partition column." },
    { name = "agent_id", type = "STRING", mode = "REQUIRED",
    description = "Short agent name (e.g. triage, risk-watcher). Cluster column." },
    { name = "agent_identity_uuid", type = "STRING", mode = "NULLABLE",
    description = "Platform-issued Agent Identity UUID (PRD §4.2). Null pre-deployment." },
    { name = "sa_email", type = "STRING", mode = "REQUIRED",
    description = "Service account the agent ran as." },
    { name = "input_summary", type = "STRING", mode = "NULLABLE",
    description = "JSON-encoded summary of input. Caller must redact PII." },
    { name = "output", type = "STRING", mode = "NULLABLE",
    description = "JSON-encoded agent output. Null on failure." },
    { name = "confidence", type = "FLOAT64", mode = "NULLABLE",
    description = "Agent-reported confidence in [0,1]. Null when not applicable." },
    { name = "latency_ms", type = "INT64", mode = "REQUIRED",
    description = "Wall-clock invocation latency in milliseconds." },
    { name = "cost_usd", type = "FLOAT64", mode = "NULLABLE",
    description = "Populated by Agent Observability link in WS-E." },
    { name = "hipaa_guard_status", type = "STRING", mode = "REQUIRED",
    description = "PASSED or TRIPPED. PRD §4.1 layer 4." },
    { name = "model_armor_findings", type = "STRING", mode = "NULLABLE",
    description = "JSON array of Model Armor findings. Null until WS-G wires it." },
    { name = "success", type = "BOOL", mode = "REQUIRED",
    description = "False on any exception path." },
    { name = "error", type = "STRING", mode = "NULLABLE",
    description = "Exception class + message on failure. Null on success." },
    { name = "human_review_routed", type = "BOOL", mode = "REQUIRED",
    description = "True when confidence < 0.7. PRD §6.1 — routing acted on by WS-D." },
  ])

  # Audit events are intentionally retained indefinitely. The default Cloud
  # Audit Log retention (400 days, ADR 0005) covers GCP-side actions; this
  # application-level log is what feeds §13 metrics and incident review.
  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "audit_log"
  }
}

# ---------------------------------------------------------------------------
# Agent outputs (PRD §6.1, spec §3.1 / §5–§8)
# ---------------------------------------------------------------------------
# Four tables that every agent module composes against. Two are BQ-canonical
# (triaged_items, risk_flags — agent writes BQ first, materializes an Airtable
# Tasks row as a side-effect), two are Airtable-canonical (goals, goal_scores
# — humans edit in Airtable, WS-B PR-2 syncs into BQ for fast Cached-Contents
# lookup by Triage). All four live under one dataset because all four are read
# during agent inference. Rationale: ADR 0009.
#
# No SA grants here. Each WS-G module grants its own agent SA write access on
# the specific table(s) it produces (PRD §4.2 SA topology; matches the
# audit-log pattern above).

resource "google_bigquery_dataset" "agent_outputs" {
  project    = var.brain_project_id
  dataset_id = "agent_outputs"
  location   = "US"
  description = join(" ", [
    "WS-C: structured outputs of Triage Agent, Risk Watcher, and Goal Steward;",
    "plus BQ-side replicas of Airtable Goals/Goal Scores for Cached-Contents",
    "queries. PRD §6.1 / spec §3.1, §5–§8. Canonicality split documented in ADR 0009.",
  ])

  labels = {
    workstream = "agent_runtime"
    component  = "outputs"
  }

  depends_on = [google_project_service.agent_runtime]
}

# Triage Agent output — one row per classified inbound signal (spec §5.1, §7).
# BQ-canonical: agent writes here first, then materializes an Airtable Tasks
# row (Source = "Triage Agent") for human review.
resource "google_bigquery_table" "triaged_items" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_outputs.dataset_id
  table_id   = "triaged_items"

  description = "Per-signal classification produced by the Triage Agent. Read by WS-D routing and downstream WS-G briefers. Spec §5.1, §7."

  # Partition by triage time so routing dashboards / hourly digests scan recent
  # windows cheaply. Cluster on the two filters every routing query uses.
  # ADR 0024: drop partitions older than 730 days; agent decisions worth ~2y
  # for trend analysis but not forever.
  time_partitioning {
    type          = "DAY"
    field         = "triaged_at"
    expiration_ms = 63072000000 # 730 days
  }
  clustering = ["severity", "source"]

  schema = jsonencode([
    { name = "item_id", type = "STRING", mode = "REQUIRED",
    description = "UUIDv4 generated by the Triage Agent." },
    { name = "triaged_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When the Triage Agent classified this signal (UTC). Partition column." },
    { name = "agent_run_id", type = "STRING", mode = "REQUIRED",
    description = "Joins to agent_audit_log.events.event_id. PRD §4.6 traceability." },
    { name = "source", type = "STRING", mode = "REQUIRED",
    description = "Signal origin: gmail | drive | airtable | calendar | chat | vantage. Cluster column." },
    { name = "source_url", type = "STRING", mode = "NULLABLE",
    description = "Permalink back to the originating signal (Gmail thread, Drive doc, etc.)." },
    { name = "source_event_ref", type = "STRING", mode = "NULLABLE",
    description = "Internal id of the input event (e.g. Gmail message-id). Used for joins back to ingestion logs." },
    { name = "input_hash", type = "STRING", mode = "REQUIRED",
    description = "SHA-256 of normalized input. Dedup key — re-classification of the same signal updates rather than duplicates." },
    { name = "ingested_at", type = "TIMESTAMP", mode = "NULLABLE",
    description = "When the source signal was first observed by the ingestion layer; differs from triaged_at when classification is delayed." },
    { name = "actionable", type = "BOOL", mode = "REQUIRED",
    description = "Spec §7.1: true iff the signal would advance one of the active goals within 60 days." },
    { name = "positive_goal_achieving", type = "STRING", mode = "NULLABLE",
    description = "Spec §7.2 PGA strength when actionable=true: strong | moderate | weak. NULL when actionable=false (Axis 1 routes non-actionable items to Trash/File/Tickle and Axis 2 isn't assessed). See ADR 0009." },
    { name = "owner_type", type = "STRING", mode = "REQUIRED",
    description = "Who handles it: brian | delegate | na." },
    { name = "owner_email", type = "STRING", mode = "NULLABLE",
    description = "Resolved owner address. Null when owner_type = 'na'." },
    { name = "action_type", type = "STRING", mode = "REQUIRED",
    description = "Recommended next action: do_now | delegate | defer | schedule | wait." },
    { name = "category", type = "STRING", mode = "NULLABLE",
    description = "GTD-style bucket: calls | computer | errands | office | schedule | team_meeting | staff | waiting_for | home." },
    { name = "task_or_project", type = "STRING", mode = "NULLABLE",
    description = "Granularity hint: task (one step) | project (multi-step)." },
    { name = "severity", type = "STRING", mode = "REQUIRED",
    description = "Routing severity: critical | high | medium | low | info. Cluster column. Drives WS-D routing matrix (spec §8.1)." },
    { name = "confidence", type = "FLOAT64", mode = "REQUIRED",
    description = "Agent-reported confidence in [0,1]." },
    { name = "human_review_routed", type = "BOOL", mode = "REQUIRED",
    description = "True when confidence < 0.7 (PRD §6.1). Mirrors agent_audit_log.events column for cross-table consistency." },
    { name = "reasoning", type = "STRING", mode = "REQUIRED",
    description = "Agent's natural-language explanation. PRD §4.6 audit discipline." },
    { name = "airtable_task_record_id", type = "STRING", mode = "NULLABLE",
    description = "Airtable Tasks 'rec...' id of the materialized human-readable row (Source = 'Triage Agent'). Null until materialization succeeds." },
    { name = "model", type = "STRING", mode = "REQUIRED",
    description = "Model identifier (e.g. gemini-2.5-flash). Powers per-model performance dashboards." },
    { name = "prompt_version", type = "STRING", mode = "REQUIRED",
    description = "Git short-sha of the prompt template at invocation time. Pairs with prompts/ directory versioning." },
    { name = "scope", type = "STRING", mode = "NULLABLE",
    description = "PKM merge (ADR 0037 §1): 'agency' | 'personal'. NULL on pre-ADR-0037 rows (backfill UPDATE sets them to 'agency'); new ingests set per signal source. Used at query time only — clustering is unchanged." },
    { name = "account_id", type = "STRING", mode = "NULLABLE",
    description = "Airtable Accounts rec... id resolved from sender email via sender_to_project_v. NULL for non-Gmail sources or unresolved senders. Enables direct account-keyed JOINs (replaces fuzzy source-field matching)." },
  ])

  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "outputs"
  }
}

# WS-D dispatch log — one row per (item_id, channel) routing event (ADR 0025).
# Insert-only by design: BQ blocks DML on streaming-buffer rows for ~30 min
# after insert, so the fan-out worker uses insert_rows_json — no UPDATE path.
resource "google_bigquery_table" "routed_events" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_outputs.dataset_id
  table_id   = "routed_events"

  description = "Per-channel dispatch log written by WS-D workers. One row per (item_id, channel). Insert-only — see ADR 0025 for why this replaces UPDATE on triaged_items.routed_to."

  time_partitioning {
    type          = "DAY"
    field         = "routed_at"
    expiration_ms = 63072000000 # 730 days, mirrors triaged_items per ADR 0024
  }
  clustering = ["item_id"]

  schema = jsonencode([
    { name = "item_id", type = "STRING", mode = "REQUIRED",
    description = "Joins to triaged_items.item_id." },
    { name = "channel", type = "STRING", mode = "REQUIRED",
    description = "Channel key. Matches routing.matrix.Channel enum values: google_chat_dm | gemini_inbox | morning_brief | rest_of_queue | airtable_view." },
    { name = "routed_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When the dispatch landed (UTC). Partition column." },
    { name = "chat_status", type = "INT64", mode = "NULLABLE",
    description = "HTTP status from the channel adapter (e.g. 200 for a successful Chat webhook POST). Null for non-HTTP channels." },
    { name = "agent_run_id", type = "STRING", mode = "NULLABLE",
    description = "Joins to agent_audit_log.events.event_id for traceback." },
  ])

  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "outputs"
  }
}

# Risk Watcher output — one row per pattern detection (spec §5.2, §6).
# BQ-canonical: detailed signal evidence + baseline snapshot live here for
# replay/audit. Risk Watcher also emits an Airtable Tasks row (Source = "Risk
# Watcher") for the human queue.
resource "google_bigquery_table" "risk_flags" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_outputs.dataset_id
  table_id   = "risk_flags"

  description = "Per-pattern risk detections produced by Risk Watcher subclasses (e-commerce / local / agency partner). Spec §5.2, §6."

  # Partition by flag time for hourly business-hours runs (spec §9.2). Cluster
  # on the two filters every triage query uses: per-account open flags by severity.
  # ADR 0024: drop partitions older than 730 days; same window as triaged_items.
  time_partitioning {
    type          = "DAY"
    field         = "flagged_at"
    expiration_ms = 63072000000 # 730 days
  }
  clustering = ["account_id", "severity"]

  schema = jsonencode([
    { name = "flag_id", type = "STRING", mode = "REQUIRED",
    description = "UUIDv4 generated by Risk Watcher." },
    { name = "flagged_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When the pattern fired (UTC). Partition column." },
    { name = "agent_run_id", type = "STRING", mode = "REQUIRED",
    description = "Joins to agent_audit_log.events.event_id. PRD §4.6 traceability." },
    { name = "account_id", type = "STRING", mode = "REQUIRED",
    description = "Airtable Accounts 'rec...' id this flag is scoped to. Cluster column. Renamed from client_id in ADR 0020." },
    { name = "project_id", type = "STRING", mode = "NULLABLE",
    description = "Airtable Projects 'rec...' id when the flag is scoped to a specific project." },
    { name = "segment", type = "STRING", mode = "REQUIRED",
    description = "Risk Watcher subclass that produced the flag: ecommerce | local | agency_partner. Spec §6.1–§6.3." },
    { name = "pattern_name", type = "STRING", mode = "REQUIRED",
    description = "Trouble-signal pattern: acknowledgment_gap | silent_after_deliverable | klaviyo_list_decline | stakeholder_change | etc. Snake-case form of spec §6 names." },
    { name = "severity", type = "STRING", mode = "REQUIRED",
    description = "critical | high | medium | low. Cluster column. Drives routing matrix the same way Triage severity does." },
    { name = "signal_evidence", type = "STRING", mode = "REQUIRED",
    description = "JSON: observed values + threshold + comparison window that triggered the pattern." },
    { name = "data_sources", type = "STRING", mode = "REPEATED",
    description = "Sources the signal was computed from: vantage | gmail | calendar | klaviyo | gbp." },
    { name = "baseline_snapshot", type = "STRING", mode = "NULLABLE",
    description = "JSON of the rolling baseline state at flag time (Memory Bank state per spec §6.1). Enables replay and human review of borderline calls." },
    { name = "confidence", type = "FLOAT64", mode = "REQUIRED",
    description = "Agent-reported confidence in [0,1]. Spec §5.2 expects ≥ 0.9 (high-recall tuning)." },
    { name = "human_review_routed", type = "BOOL", mode = "REQUIRED",
    description = "True when confidence < 0.7 (PRD §6.1). Mirrors agent_audit_log.events and triaged_items so WS-D can route on the column directly without joining to the audit log." },
    { name = "reasoning", type = "STRING", mode = "REQUIRED",
    description = "Agent's natural-language explanation of why this pattern fired." },
    { name = "airtable_task_record_id", type = "STRING", mode = "NULLABLE",
    description = "Airtable Tasks 'rec...' id of the materialized human-readable row (Source = 'Risk Watcher')." },
    { name = "resolved_at", type = "TIMESTAMP", mode = "NULLABLE",
    description = "When the flag was acknowledged or auto-resolved. Null while open." },
    { name = "resolution_note", type = "STRING", mode = "NULLABLE",
    description = "Human or agent note explaining the resolution." },
    { name = "model", type = "STRING", mode = "REQUIRED",
    description = "Model identifier." },
    { name = "prompt_version", type = "STRING", mode = "REQUIRED",
    description = "Git short-sha of the prompt template at invocation time." },
  ])

  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "outputs"
  }
}

# Signal feedback — operator verdicts on signals (ADR 0060). One row per verdict.
# Keyed by the recurring (account_id, pattern_name) TUPLE, not a flag instance,
# so a "noise" verdict survives flag re-emission (Risk Watcher mints a fresh
# flag_id every run). Captured conversationally via the `record_feedback` MCP
# write tool; consumed by the Risk Watcher suppression gate (ADR 0060 §3).
resource "google_bigquery_table" "signal_feedback" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_outputs.dataset_id
  table_id   = "signal_feedback"

  description = "Operator feedback on signals (ADR 0060). verdict='noise' rows gate Risk Watcher / Triage emission for the (account_id, pattern_name) tuple until mute_until. scope discriminates risk | triage | draft (ADR 0037)."

  # Partition by verdict time; low volume (operator-authored, a handful/week)
  # but partitioning keeps the suppression-gate scan cheap and matches the
  # ADR 0024 730-day window used by risk_flags / triaged_items. Cluster on the
  # two columns the gate filters: scope + account.
  time_partitioning {
    type          = "DAY"
    field         = "created_at"
    expiration_ms = 63072000000 # 730 days
  }
  clustering = ["scope", "account_id"]

  schema = jsonencode([
    { name = "feedback_id", type = "STRING", mode = "REQUIRED",
    description = "UUIDv4 generated by the record_feedback MCP tool." },
    { name = "created_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When the operator gave the verdict (UTC). Partition column." },
    { name = "scope", type = "STRING", mode = "REQUIRED",
    description = "Signal class this verdict applies to: risk | triage | draft (ADR 0037 scope discriminator)." },
    { name = "account_id", type = "STRING", mode = "NULLABLE",
    description = "Airtable Accounts 'rec...' id the verdict is scoped to. Resolved from account_name by the tool. Cluster column. NULL only for account-agnostic draft-tone feedback." },
    { name = "pattern_name", type = "STRING", mode = "NULLABLE",
    description = "For scope='risk': the risk_flags.pattern_name this applies to. NULL = applies to ALL patterns on the account." },
    { name = "verdict", type = "STRING", mode = "REQUIRED",
    description = "noise | valid | wrong_tone | wrong_target. Only 'noise' drives the suppression gate; others inform Stage-2 tuning (ADR 0060 §4)." },
    { name = "note", type = "STRING", mode = "NULLABLE",
    description = "Operator's free-text rationale (e.g. 'they always go quiet in summer')." },
    { name = "mute_until", type = "TIMESTAMP", mode = "NULLABLE",
    description = "For verdict='noise': suppress through this time. NULL = indefinite. Time-boxing guards against permanently hiding a genuine turn." },
    { name = "source_flag_id", type = "STRING", mode = "NULLABLE",
    description = "The specific risk_flags.flag_id / triaged_items id that prompted the verdict, for traceability." },
    { name = "created_by", type = "STRING", mode = "REQUIRED",
    description = "Author of the verdict. Always 'operator' in v1 (only the operator gives feedback)." },
  ])

  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "outputs"
  }
}

# Goals — Airtable-canonical (humans edit in Airtable Goals); WS-B PR-2 syncs
# into this BQ table for Cached-Contents lookup by the Triage Agent (PRD §6.3).
# Schema mirrors airtable/schema.json Goals plus sync metadata.
resource "google_bigquery_table" "goals" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_outputs.dataset_id
  table_id   = "goals"

  description = "BQ-side replica of Airtable Goals. Read by Triage Agent via Cached Contents (filter: status='Active' AND horizon IN ('Quarterly','1-year')). Source of truth is Airtable. Spec §3.1, goal_hierarchy_v0.1.md."

  # No partitioning: total volume is ~30–100 rows (10y + 3y + 1y + Quarterly
  # per goal_hierarchy_v0.1.md). Cluster on the Cached-Contents filter columns.
  clustering = ["status", "horizon"]

  schema = jsonencode([
    { name = "goal_id", type = "STRING", mode = "REQUIRED",
    description = "Airtable record id ('rec...'). Source of truth." },
    { name = "goal_name", type = "STRING", mode = "REQUIRED",
    description = "Human-readable goal name." },
    { name = "owner_email", type = "STRING", mode = "REQUIRED",
    description = "Resolved from the Owner link → Team.Email at sync time." },
    { name = "horizon", type = "STRING", mode = "REQUIRED",
    description = "10-year | 3-year | 1-year | quarterly | weekly. Cluster column." },
    { name = "parent_goal_id", type = "STRING", mode = "NULLABLE",
    description = "Airtable record id of the parent goal. Required upstream unless horizon = '10-year'; nullable in BQ since the constraint is enforced at sync time." },
    { name = "area_of_focus", type = "STRING", mode = "NULLABLE",
    description = "Revenue | Team | Product | Personal | Education | Other." },
    { name = "description", type = "STRING", mode = "NULLABLE",
    description = "What the goal is in human language." },
    { name = "tactics", type = "STRING", mode = "NULLABLE",
    description = "The 'how' — specific moves planned to achieve it." },
    { name = "metrics", type = "STRING", mode = "NULLABLE",
    description = "Numeric or observable definition of success." },
    { name = "status", type = "STRING", mode = "REQUIRED",
    description = "Active | Achieved | Abandoned | Paused. Cluster column." },
    { name = "last_reviewed", type = "DATE", mode = "NULLABLE",
    description = "Last review date written by Goal Steward (WS-G6) weekly cadence." },
    { name = "created_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When this row was first observed by the WS-B sync." },
    { name = "updated_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When the upstream Airtable row last changed." },
    { name = "last_synced_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When the WS-B sync last refreshed this row." },
  ])

  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "outputs"
  }
}

# Goal Scores — weekly self-assessment time series (spec §6.1, goal_hierarchy
# weekly cadence). Airtable-canonical via the Goal Scores table; replicated
# into BQ by WS-B PR-2. Goal Steward may also write directly (agent_run_id
# tracks that path).
resource "google_bigquery_table" "goal_scores" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_outputs.dataset_id
  table_id   = "goal_scores"

  description = "Weekly 1-10 self-assessment per active goal. Feeds Weekly Synthesizer + Goal Steward trend alerts (drop ≥ 2 points WoW; no score 14+ days). Spec §6.1, goal_hierarchy_v0.1.md."

  # Partition monthly: ~12 active goals × 52 weeks ≈ 600 rows/yr. DAY would
  # leave most partitions with one row; MONTH still allows efficient retention
  # and trend queries.
  time_partitioning {
    type  = "MONTH"
    field = "week_of"
  }
  clustering = ["goal_id"]

  schema = jsonencode([
    { name = "score_id", type = "STRING", mode = "REQUIRED",
    description = "Airtable record id when synced; UUIDv4 if Goal Steward wrote directly." },
    { name = "week_of", type = "DATE", mode = "REQUIRED",
    description = "Monday of the week being scored. Partition column." },
    { name = "goal_id", type = "STRING", mode = "REQUIRED",
    description = "FK to goals.goal_id (Airtable Goals 'rec...'). Cluster column." },
    { name = "score", type = "INT64", mode = "REQUIRED",
    description = "1-10 self-assessment. Validated upstream." },
    { name = "notes", type = "STRING", mode = "NULLABLE",
    description = "Why this score." },
    { name = "scorer_email", type = "STRING", mode = "REQUIRED",
    description = "Email of the team member who recorded the score (resolved from Scorer link at sync time)." },
    { name = "scored_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "Wall-clock time the score was recorded." },
    { name = "agent_run_id", type = "STRING", mode = "NULLABLE",
    description = "Joins to agent_audit_log.events.event_id when Goal Steward wrote directly. Null when entered via Airtable UI." },
    { name = "last_synced_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When the WS-B sync last refreshed this row." },
  ])

  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "outputs"
  }
}

# Morning Briefs — one row per (recipient, local_date) per ADR 0029.
# Written by the WS-G3 Morning Brief Cloud Run Job after a successful
# Gmail draft. Per-recipient-per-day dedup is enforced at the writer
# level via SELECT pre-check (mirrors ADR 0026's idiom).
resource "google_bigquery_table" "morning_briefs" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_outputs.dataset_id
  table_id   = "morning_briefs"

  description = "Per-recipient daily Morning Brief audit row. One per (recipient_email, local_date). PRD §5.6 / ADR 0029."

  time_partitioning {
    type          = "DAY"
    field         = "generated_at"
    expiration_ms = 63072000000 # 730 days, mirrors triaged_items per ADR 0024
  }
  clustering = ["recipient_email", "local_date"]

  schema = jsonencode([
    { name = "brief_id", type = "STRING", mode = "REQUIRED",
    description = "UUIDv4 generated by the Morning Brief writer." },
    { name = "agent_run_id", type = "STRING", mode = "REQUIRED",
    description = "Joins to agent_audit_log.events.event_id. PRD §4.6." },
    { name = "recipient_email", type = "STRING", mode = "REQUIRED",
    description = "Workspace user the brief was drafted for. v1 = owner@example.com only. Cluster column." },
    { name = "local_date", type = "DATE", mode = "REQUIRED",
    description = "Calendar date in BRIEF_TIMEZONE (default America/Los_Angeles) for which the brief was composed. Dedup key together with recipient_email. Cluster column." },
    { name = "generated_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When the brief was composed (UTC). Partition column." },
    { name = "body_markdown", type = "STRING", mode = "REQUIRED",
    description = "The full markdown body the agent rendered. Quiet days store the one-line 'Quiet day' body — never empty." },
    { name = "sections_used", type = "STRING", mode = "REPEATED",
    description = "Section keys included in the body: top_three | drafts_awaiting_review | risk_flags | calendar | rest_of_queue." },
    { name = "gmail_draft_id", type = "STRING", mode = "NULLABLE",
    description = "Draft id returned by Gmail users.drafts.create. Null when dedup_skipped or the Gmail leg failed (BQ row remains audit trail)." },
    { name = "dedup_skipped", type = "BOOL", mode = "REQUIRED",
    description = "True when a brief for (recipient_email, local_date) already existed; the writer skipped the Gmail draft + this row's main fields are minimal." },
    { name = "dedup_existing_brief_id", type = "STRING", mode = "NULLABLE",
    description = "When dedup_skipped=true, the brief_id of the row this run would have duplicated." },
    { name = "prompt_version", type = "STRING", mode = "REQUIRED",
    description = "Prompt template version (e.g. v1). Pairs with prompts/morning_brief/<version>.md so prompt iterations are auditable in BQ." },
    { name = "model", type = "STRING", mode = "REQUIRED",
    description = "Model identifier (e.g. gemini-2.5-flash). Powers per-model performance dashboards." },
    { name = "latency_ms", type = "INT64", mode = "REQUIRED",
    description = "End-to-end agent latency including BQ reads, calendar fetch, LLM call, and Gmail draft create." },
    { name = "success", type = "BOOL", mode = "REQUIRED",
    description = "True when the agent completed without raising. False rows carry error and skip gmail_draft_id." },
    { name = "error", type = "STRING", mode = "NULLABLE",
    description = "Type and message of the exception when success=false." },
  ])

  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "outputs"
  }
}

# Per-recipient daily Evening Reflection audit row, written by the WS-G4
# Cloud Run Job. Schema mirrors morning_briefs field-for-field so per-day
# "did the daily ritual happen on both ends?" queries are trivial. Per
# ADR 0036 §5.
resource "google_bigquery_table" "evening_reflections" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_outputs.dataset_id
  table_id   = "evening_reflections"

  description = "Per-recipient-per-mode daily Evening Reflection audit row. One per (recipient_email, local_date, mode). PRD §5.4 Track 2 / ADRs 0036, 0040."

  time_partitioning {
    type          = "DAY"
    field         = "generated_at"
    expiration_ms = 63072000000 # 730 days, mirrors morning_briefs per ADR 0024
  }
  clustering = ["recipient_email", "local_date"]

  schema = jsonencode([
    { name = "reflection_id", type = "STRING", mode = "REQUIRED",
    description = "UUIDv4 generated by the Evening Reflection writer." },
    { name = "agent_run_id", type = "STRING", mode = "REQUIRED",
    description = "Joins to agent_audit_log.events.event_id. PRD §4.6." },
    { name = "recipient_email", type = "STRING", mode = "REQUIRED",
    description = "Workspace user the reflection was drafted for. v1 = owner@example.com only. Cluster column." },
    { name = "local_date", type = "DATE", mode = "REQUIRED",
    description = "Calendar date in REFLECTION_TIMEZONE (default America/Los_Angeles) the reflection covers. Dedup key together with recipient_email. Cluster column." },
    { name = "generated_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When the reflection was composed (UTC). Partition column." },
    { name = "body_markdown", type = "STRING", mode = "REQUIRED",
    description = "The full markdown body the agent rendered. Unremarkable days store the one-paragraph fallback body — never empty." },
    { name = "sections_used", type = "STRING", mode = "REPEATED",
    description = "Reader keys whose data made it into the prompt: completed_tasks | triaged_today | calendar | morning_brief | active_risk_flags." },
    { name = "gmail_draft_id", type = "STRING", mode = "NULLABLE",
    description = "Draft id returned by Gmail users.drafts.create. Null when dedup_skipped or the Gmail leg failed (BQ row remains audit trail)." },
    { name = "dedup_skipped", type = "BOOL", mode = "REQUIRED",
    description = "True when a reflection for (recipient_email, local_date) already existed; the writer skipped the Gmail draft + this row's main fields are minimal." },
    { name = "dedup_existing_reflection_id", type = "STRING", mode = "NULLABLE",
    description = "When dedup_skipped=true, the reflection_id of the row this run would have duplicated." },
    { name = "prompt_version", type = "STRING", mode = "REQUIRED",
    description = "Prompt template version (e.g. v1). Pairs with prompts/evening_reflection/<version>.md so prompt iterations are auditable in BQ." },
    { name = "model", type = "STRING", mode = "REQUIRED",
    description = "Model identifier (e.g. gemini-2.5-flash). Powers per-model performance dashboards." },
    { name = "latency_ms", type = "INT64", mode = "REQUIRED",
    description = "End-to-end agent latency including BQ reads, calendar fetch, LLM call, and Gmail draft create." },
    { name = "success", type = "BOOL", mode = "REQUIRED",
    description = "True when the agent completed without raising. False rows carry error and skip gmail_draft_id." },
    { name = "error", type = "STRING", mode = "NULLABLE",
    description = "Type and message of the exception when success=false." },
    { name = "mode", type = "STRING", mode = "NULLABLE",
    description = "ADR 0040: prompt | reflect. NULL on pre-PR-C rows (interpreted as 'reflect' at read time per ADR 0040 §7). Dedup key together with recipient_email + local_date so the 16:00 PT prompt tick doesn't collide with the 21:00 PT reflect tick on the same day." },
    { name = "reflection_doc_id", type = "STRING", mode = "NULLABLE",
    description = "ADR 0044 — Drive file id of the daily Reflection Doc in Brain/Areas/Reflections/. Populated by REFLECT-mode rows that successfully created the Doc. NULL on PROMPT mode (Gmail-draft surface) and on REFLECT rows that fell back to Gmail." },
    { name = "reflection_doc_url", type = "STRING", mode = "NULLABLE",
    description = "ADR 0044 — Drive webViewLink for the Reflection Doc. The Chat-card notification embeds this URL." },
  ])

  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "outputs"
  }
}

# Samsung Notes corpus — one row per (note_id, revision_id) per ADR 0031.
# Written by the WS-G notes ingestor Cloud Run Job after a successful
# Vertex Gemini multimodal extraction. The same row's drive_file_id +
# revision_id combo is the dedup key on re-list (the writer pre-checks
# via SELECT before any Vertex spend).
resource "google_bigquery_table" "notes" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_outputs.dataset_id
  table_id   = "notes"

  description = "Samsung Notes corpus — Markdown extracted from PDFs shared into the Brain Inbox Drive folders. ADR 0031."

  time_partitioning {
    type          = "DAY"
    field         = "ingested_at"
    expiration_ms = 63072000000 # 730 days, mirrors triaged_items per ADR 0024
  }
  clustering = ["hipaa_isolated", "source_drive_file_id"]

  schema = jsonencode([
    { name = "note_id", type = "STRING", mode = "REQUIRED",
    description = "Stable note identifier — equals source_drive_file_id. New revisions of the same note share note_id but get a new row keyed (note_id, revision_id)." },
    { name = "revision_id", type = "STRING", mode = "REQUIRED",
    description = "Drive headRevisionId at ingest time. Re-edits in Samsung Notes that the user re-shares produce a new revision_id and a fresh row." },
    { name = "ingested_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When the ingestor wrote this row (UTC). Partition column." },
    { name = "created_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "Drive modifiedTime of the source PDF — when the user last shared/edited the note." },
    { name = "source_drive_file_id", type = "STRING", mode = "REQUIRED",
    description = "Drive file id. Cluster column." },
    { name = "source_drive_url", type = "STRING", mode = "REQUIRED",
    description = "Drive webViewLink — humans click through here to see the original (preserves graphics + handwriting)." },
    { name = "filename", type = "STRING", mode = "REQUIRED",
    description = "Drive filename at ingest time. Used as the triage envelope's subject." },
    { name = "markdown_content", type = "STRING", mode = "NULLABLE",
    description = "Gemini-extracted Markdown with inline [Image: caption] for graphics. NULL only when extraction_method='failed'." },
    { name = "extraction_method", type = "STRING", mode = "REQUIRED",
    description = "Extractor identifier: gemini-2.5-flash | failed. Reserved for future Document AI fallback if Gemini hallucination ever requires it." },
    { name = "extraction_confidence", type = "FLOAT64", mode = "REQUIRED",
    description = "Self-rated extraction quality in [0,1] from the Vertex model. Phase 3 RAG retrieval can filter on this." },
    { name = "extraction_notes", type = "STRING", mode = "NULLABLE",
    description = "Free-form extractor diagnostic (e.g. 'page 3 illegible'). NULL on clean extractions." },
    { name = "page_count", type = "INT64", mode = "REQUIRED",
    description = "Page count reported by the extractor. 0 on extraction failure." },
    { name = "hipaa_isolated", type = "BOOL", mode = "REQUIRED",
    description = "True when the source folder was Brain Inbox/Notes-HIPAA/. Phase 2 readers (Morning Brief notes section) filter hipaa_isolated=false. Cluster column." },
    { name = "triaged_item_id", type = "STRING", mode = "NULLABLE",
    description = "Back-ref to agent_outputs.triaged_items.item_id once the Triage Reasoning Engine classifies the note. NULL until classification or for HIPAA notes (which short-circuit at the BaseAgent guard)." },
    { name = "note_kind", type = "STRING", mode = "NULLABLE",
    description = "PKM merge (ADR 0037 §2): kind of note — inbox | area | resource | archive | galaxy. Defaults 'inbox' at write time; flips via UPDATE for Galaxy promotion. Drives kind-gated triage publish (ADR 0037 §6) — only 'inbox' notes publish to asb-triage-input. NULL on pre-ADR-0037 rows (backfill sets them to 'inbox')." },
    { name = "scope", type = "STRING", mode = "NULLABLE",
    description = "PKM merge (ADR 0037 §1): 'agency' | 'personal'. NULL on pre-ADR-0037 rows; backfill UPDATE sets them to 'personal' (pre-merge corpus is Samsung Notes from the user's Tab S9 — all personal captures per ADR 0031). New ingests set per source folder. Cluster keys unchanged — query-time filter only." },
    { name = "embedding_content_hash", type = "STRING", mode = "NULLABLE",
    description = "SHA-256 of markdown_content at embed time. Idempotency guard for the embedder (ADR 0038 §4) — if the hash matches, skip re-embed. NULL on pre-ADR-0038 rows; populated by the backfill job." },
    { name = "embedding", type = "FLOAT64", mode = "REPEATED",
    description = "768-dim text-embedding-005 vector over markdown_content (ADR 0038 §1, §2). Used by BQ VECTOR_SEARCH for semantic recall (Reflection anchors, Brag Spotter clustering, Phase 5 Connector). Empty array on rows whose extraction_method='failed' or pre-backfill rows." },
    { name = "embedding_model", type = "STRING", mode = "NULLABLE",
    description = "Embedding model identifier — 'text-embedding-005' for v1 (ADR 0038 §1). NULL on pre-ADR-0038 rows. Setting to NULL via UPDATE triggers re-embed via the idempotency guard." },
    { name = "embedding_generated_at", type = "TIMESTAMP", mode = "NULLABLE",
    description = "When the embedding was last generated (UTC). NULL on pre-ADR-0038 rows. ADR 0038 §4." },
    # ADR 0046 — Calendar ingester additive columns. Both NULLABLE so
    # this is an additive schema change that does NOT trigger a
    # `must be replaced` diff against the existing notes table. Drive
    # notes leave both at NULL.
    { name = "external_id", type = "STRING", mode = "NULLABLE",
    description = "External system identifier (Google Calendar event id for note_kind='calendar_event' rows). NULL for Drive-derived notes. MERGE key for the Calendar ingester (ADR 0046 §2)." },
    { name        = "event_metadata", type = "RECORD", mode = "NULLABLE",
      description = "Calendar event metadata (ADR 0046 §2). NULL for non-calendar rows. Carries start/end timestamps + attendees + organizer + location + status so the Knowledge Surfacer can render structured citations and answer 'when did I last meet with X' queries.",
      fields = [
        { name = "start", type = "STRING", mode = "NULLABLE",
        description = "ISO 8601 start. STRING (not TIMESTAMP) so all-day events round-trip cleanly." },
        { name = "end", type = "STRING", mode = "NULLABLE",
        description = "ISO 8601 end." },
        { name = "attendees", type = "STRING", mode = "REPEATED",
        description = "Lowercased attendee email addresses. Empty array when the event has no attendees." },
        { name = "organizer", type = "STRING", mode = "NULLABLE",
        description = "Lowercased organizer email." },
        { name = "location", type = "STRING", mode = "NULLABLE",
        description = "Free-text location string from Calendar v3 event.location." },
        { name = "status", type = "STRING", mode = "NULLABLE",
        description = "Calendar v3 event.status: 'confirmed' | 'tentative' | 'cancelled' (cancelled events are filtered before write)." },
    ] },
  ])

  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "outputs"
  }
}

# Personal decision journal — captures the choice, prediction, confidence,
# and 30/90/365d retrospectives. Drafted by Evening Reflection v2 (Phase 1
# / ADR 0039) or directly via the Captures form. Surfaced for retrospective
# review by asb-decisions-reviewer (Phase 2 / ADR 0040).
resource "google_bigquery_table" "decisions" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_outputs.dataset_id
  table_id   = "decisions"

  description = "Personal decision journal — choice + prediction + confidence + 30/90/365d retros. Drafted by Reflection v2 / direct via Captures form; reviewed by asb-decisions-reviewer. ADR 0037 / 0040."

  time_partitioning {
    type          = "DAY"
    field         = "decided_at"
    expiration_ms = 63072000000 # 730 days
  }
  clustering = ["status"]

  schema = jsonencode([
    { name = "decision_id", type = "STRING", mode = "REQUIRED",
    description = "UUIDv4. Stable across edits — refinement and retrospective writes update the row in place." },
    { name = "decided_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When the decision was made (UTC). Partition column." },
    { name = "title", type = "STRING", mode = "REQUIRED",
    description = "Short headline — 'Hire X for Y role', 'Pursue MBA elective Z'." },
    { name = "context", type = "STRING", mode = "NULLABLE",
    description = "What was happening when the decision was made. Free-form prose." },
    { name = "alternatives", type = "STRING", mode = "REPEATED",
    description = "Other options considered. Empty on draft-status rows pre-refinement." },
    { name = "choice", type = "STRING", mode = "REQUIRED",
    description = "What was actually chosen." },
    { name = "prediction", type = "STRING", mode = "NULLABLE",
    description = "Testable prediction at 90 days — 'this will result in X observable outcome.' NULL on draft rows." },
    { name = "confidence", type = "FLOAT64", mode = "NULLABLE",
    description = "Self-rated confidence in [0,1] at decision time. NULL on draft rows." },
    { name = "review_30_at", type = "DATE", mode = "REQUIRED",
    description = "Date the 30d retrospective is due. Reviewer agent compares to CURRENT_DATE() to surface." },
    { name = "review_90_at", type = "DATE", mode = "REQUIRED",
    description = "Date the 90d retrospective is due." },
    { name = "review_365_at", type = "DATE", mode = "REQUIRED",
    description = "Date the 365d retrospective is due." },
    { name = "status", type = "STRING", mode = "REQUIRED",
    description = "Lifecycle: draft | pending | reviewed_30 | reviewed_90 | reviewed_365 | abandoned. Cluster column. Routing fan-out polls WHERE status='draft' to surface refinement prompts." },
    { name = "source_reflection_id", type = "STRING", mode = "NULLABLE",
    description = "Joins to the Reflection that auto-drafted this decision. NULL for direct (Captures form) entries." },
    { name = "source_voice_note_id", type = "STRING", mode = "NULLABLE",
    description = "Joins to agent_outputs.notes.note_id when extracted from a voice memo. Provenance audit trail." },
    { name = "refined_at", type = "TIMESTAMP", mode = "NULLABLE",
    description = "When the draft was refined to pending (alternatives + prediction + confidence filled in). NULL until refinement." },
    { name = "retrospective_30", type = "STRING", mode = "NULLABLE",
    description = "Free-form retrospective at 30d. Captured manually; reviewer agent surfaces; decision-maker fills in." },
    { name = "retrospective_90", type = "STRING", mode = "NULLABLE",
    description = "Free-form retrospective at 90d." },
    { name = "retrospective_365", type = "STRING", mode = "NULLABLE",
    description = "Free-form retrospective at 365d." },
    { name = "calibration_score", type = "FLOAT64", mode = "NULLABLE",
    description = "After-the-fact calibration: how accurate was the prediction? In [0,1]. Captured at the 90d retrospective by convention." },
    { name = "agent_run_id", type = "STRING", mode = "NULLABLE",
    description = "Joins to agent_audit_log.events.event_id when the row was written by an agent. NULL for human-entered rows." },
  ])

  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "outputs"
  }
}

# Personal wins log — auto-extracted by Reflection v2 (Phase 1) and Brag
# Spotter (Phase 3) from triaged_items, routed_events, notes, decisions,
# reflections. Surfaces for performance reviews + quarterly reflection.
resource "google_bigquery_table" "wins" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_outputs.dataset_id
  table_id   = "wins"

  description = "Personal wins log — auto-extracted from triaged_items, routed_events, notes, decisions, reflections by Brag Spotter (Phase 3) and Reflection v2 (Phase 1). ADR 0037."

  time_partitioning {
    type          = "DAY"
    field         = "captured_at"
    expiration_ms = 63072000000 # 730 days
  }
  clustering = ["source_kind"]

  schema = jsonencode([
    { name = "win_id", type = "STRING", mode = "REQUIRED",
    description = "UUIDv4." },
    { name = "captured_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When the win was logged (UTC). Partition column." },
    { name = "week_of", type = "DATE", mode = "REQUIRED",
    description = "Monday of the week the win occurred. Used for weekly aggregation in Brag Spotter; clusters Sunday-evening digests by ISO week." },
    { name = "source_kind", type = "STRING", mode = "REQUIRED",
    description = "Where it was extracted from: reflection | brag_spotter | triaged_item | routed_event | note | decision | manual. Cluster column." },
    { name = "source_id", type = "STRING", mode = "NULLABLE",
    description = "ID of the originating row (reflection_id / item_id / note_id / etc.). NULL for manual entries." },
    { name = "title", type = "STRING", mode = "REQUIRED",
    description = "Short headline — 'Closed Acme Corp Q2 contract', 'Got A on Strategy midterm'." },
    { name = "summary", type = "STRING", mode = "NULLABLE",
    description = "Free-form prose describing what happened and why it counts as a win." },
    { name = "evidence_links", type = "STRING", mode = "REPEATED",
    description = "URLs or BQ row references that back the win. Used by Brag Spotter to assemble the weekly digest." },
    { name = "agent_run_id", type = "STRING", mode = "NULLABLE",
    description = "Joins to agent_audit_log.events.event_id when the row was written by an agent." },
  ])

  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "outputs"
  }
}

# Auto-discovered semantic links between notes (cosine similarity ≥ threshold).
# Populated by the Phase 5 Connector job — declared in Phase 0 (empty) so
# Phase 5 ships without a follow-up DDL PR. ADR 0038 §5.
resource "google_bigquery_table" "notes_links" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_outputs.dataset_id
  table_id   = "notes_links"

  description = "Links between notes — semantic (Librarian VECTOR_SEARCH neighbors, cosine ≥ 0.78) and explicit (user-typed [[X]] wikilinks from ADR 0053). ADR 0038 §5 + ADR 0053."

  time_partitioning {
    type          = "DAY"
    field         = "computed_at"
    expiration_ms = 63072000000 # 730 days
  }
  clustering = ["source_note_id"]

  schema = jsonencode([
    { name = "source_note_id", type = "STRING", mode = "REQUIRED",
    description = "Joins to agent_outputs.notes.note_id. The note this link starts from. Cluster column." },
    { name = "target_note_id", type = "STRING", mode = "REQUIRED",
    description = "Joins to agent_outputs.notes.note_id. The linked note." },
    { name = "similarity", type = "FLOAT64", mode = "REQUIRED",
    description = "Cosine similarity in [0,1] for semantic edges; 1.0 for explicit wikilink edges (user-asserted at max confidence)." },
    { name = "computed_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "When the link was computed/written (UTC). Partition column." },
    # ADR 0053 — additive NULLABLE column distinguishing edge classes.
    # Existing pre-0053 rows are NULL; readers treat NULL as 'semantic'.
    { name = "link_type", type = "STRING", mode = "NULLABLE",
    description = "Edge class: 'semantic' (Librarian VECTOR_SEARCH neighbor, ADR 0045) | 'wikilink' (user-typed [[X]] in markdown_content, ADR 0053). NULL on pre-ADR-0053 rows (interpreted as 'semantic')." },
  ])

  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "outputs"
  }
}

# ---------------------------------------------------------------------------
# Agent state — small ingestor watermarks (no TTL)
# ---------------------------------------------------------------------------
# Per ADR 0031 §6: a watermark per watched Drive folder so the ingestor's
# Drive `q=` filter can use `modifiedTime > '<watermark>'` and avoid full
# folder scans every tick. Insert-only — readers take the most-recent row
# per folder. Volume is one row every 10 minutes per folder × 2 folders =
# ~12 rows/hour, ~100k/year. No partition or TTL needed.

resource "google_bigquery_dataset" "agent_state" {
  project     = var.brain_project_id
  dataset_id  = "agent_state"
  location    = "US"
  description = "Small operational state for agents (watermarks, run-locks). Distinct from agent_outputs (canonical agent decisions) and agent_audit_log (per-invocation audit). ADR 0031."

  labels = {
    workstream = "agent_runtime"
    component  = "state"
  }

  depends_on = [google_project_service.agent_runtime]
}

resource "google_bigquery_table" "notes_ingestor_watermark" {
  project    = var.brain_project_id
  dataset_id = google_bigquery_dataset.agent_state.dataset_id
  table_id   = "notes_ingestor_watermark"

  description = "Per-Drive-folder modifiedTime watermark for the notes ingestor. Insert-only; readers take the most-recent row per folder_path. ADR 0031."

  clustering = ["folder_path"]

  schema = jsonencode([
    { name = "folder_path", type = "STRING", mode = "REQUIRED",
    description = "Drive folder id of the watched folder. Cluster column." },
    { name = "last_modified_time_seen", type = "TIMESTAMP", mode = "REQUIRED",
    description = "Highest Drive modifiedTime processed in the most-recent successful tick for this folder. Drives the next tick's `modifiedTime > <watermark>` filter." },
    { name = "updated_at", type = "TIMESTAMP", mode = "REQUIRED",
    description = "Wall-clock time of this watermark write. Tie-breaker for 'most recent' selection." },
  ])

  deletion_protection = true

  labels = {
    workstream = "agent_runtime"
    component  = "state"
  }
}
